# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toginfo < Formula
  desc "Entur-powered train departures CLI"
  homepage "https://github.com/trskare/toginfo"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.3/toginfo_0.1.3_darwin_amd64.tar.gz"
      sha256 "402cb61c6e24a7c0940b26e835e6342d1cb788de486057ba55e941b0f97e9cc8"

      def install
        bin.install "toginfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.3/toginfo_0.1.3_darwin_arm64.tar.gz"
      sha256 "3bef82a9ac3d7f07e2250f0415dbd562f4453c5db61ef4ba58c660fc1b600f1c"

      def install
        bin.install "toginfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.3/toginfo_0.1.3_linux_amd64.tar.gz"
      sha256 "3e3e4609013bacbde1d8f20f15aec7e9a60fde3538040f5e1c7aa414e655c16b"
      def install
        bin.install "toginfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.3/toginfo_0.1.3_linux_arm64.tar.gz"
      sha256 "f2cdb3d002a30f71a2051883f2c80c42eee0759a6ed8c09aad34a99e12d83f6f"
      def install
        bin.install "toginfo"
      end
    end
  end

  test do
    output = shell_output("#{bin}/toginfo -clear-cache")
    assert_match "Cache cleared.", output
  end
end
