# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toginfo < Formula
  desc "Entur-powered train departures CLI"
  homepage "https://github.com/trskare/toginfo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.0/toginfo_0.1.0_darwin_amd64.tar.gz"
      sha256 "ad9e76eb3c89f0adf14c2ae48c4bc1a42ab9ab27a2bf19b8be586392cb593538"

      def install
        bin.install "toginfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.0/toginfo_0.1.0_darwin_arm64.tar.gz"
      sha256 "e399622b41d0cb9af93cb4b904d68d63702418bfceacfe6d04ac3112e3573ab7"

      def install
        bin.install "toginfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.0/toginfo_0.1.0_linux_amd64.tar.gz"
      sha256 "7d21e0968ce3120f64866e8b2f2b954c8e8a74dd9eb8b0804d408d39c1224a80"
      def install
        bin.install "toginfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trskare/toginfo/releases/download/v0.1.0/toginfo_0.1.0_linux_arm64.tar.gz"
      sha256 "cecac0317f7d90ba628b19f356bf33883459bd515ea97fcebf11ac3cc1f3c8bf"
      def install
        bin.install "toginfo"
      end
    end
  end

  test do
    output = shell_output("#{bin}/toginfo -clear-cache")
    assert_match "Cache cleared.", output
  end
end
